# Generated by Django 5.0.4 on 2024-04-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_type',
            field=models.CharField(choices=[('$', 'USD'), ("So'm", 'UZS')], default="So'm", max_length=30),
        ),
    ]
